branch-defaults:
  default:
    environment: TweetMapNode-dev
global:
  application_name: TweetMapNode
  default_ec2_keyname: cloudKP
  default_platform: Node.js
  default_region: us-west-2
  profile: null
  sc: null
